<?php
/**
* Webkul Software
*
* @category  Webkul
* @package   Webkul_MpBraintree
* @author    Webkul
* @copyright Copyright (c) 2010-2017 Webkul Software Private Limited (https://webkul.com)
* @license   https://store.webkul.com/license.html
*/
$_helper = $this->helper('Webkul\Marketplace\Helper\Data');
$isPartner= $_helper->isSeller();
$magentoCurrentUrl = $block->getCurrentUrl();
$isBraintreeEnable = $block->getIsBraintreeEnable();
$isSellerGroup = $_helper->isSellerGroupModuleInstalled();
?>
<nav class="wk-mp-menu wk-mp-main">
    <ul id="wk-mp-nav">
        <?php
        if($isPartner && $isBraintreeEnable){ ?>
          <?php if(($isSellerGroup && $_helper->isAllowedAction('mpbraintree/braintreeaccount/index')) || !$isSellerGroup) { ?>
            <li class="nav item notification-link level-0 <?php echo strpos($magentoCurrentUrl,'mpbraintree/braintreeaccount/index')? "current active":"";?>">
                <a href="<?php echo $block->getUrl('mpbraintree/braintreeaccount/index', ['_secure' => $this->getRequest()->isSecure()]); ?>">
                    <?php /* @escapeNotVerified */ echo __('Braintree Vendor Details') ?>
                </a>
            </li>
          <?php } ?>
        <?php } ?>
    </ul>
</nav>
