<div class="loading-container">
    <p><?php echo __('Loading orders. Please wait.') ?></p>
    <div class="loading-image"></div>
</div>
<div id="ordersview-container" class="embedded-iframe-container"></div>
<script>
    require(['jquery', 'loadiframe' ],
        function ($, loadiframe) {
            $(function () {
                loadiframe.load('<?php echo $this->getIframeUrl(); ?>');
            });
        });
</script>