<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var \Magento\Review\Block\Product\ReviewRenderer $block */

$url = $block->getReviewsUrl() . '#reviews';
$urlForm = $block->getReviewsUrl() . '#review-form';
?>
<?php 
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$product = $block->getProduct();
$simpleProd = '';
if($product->getTypeId() == 'grouped'):
$groupedProduct = $objectManager->create('Magento\GroupedProduct\Block\Product\View\Type\Grouped');
$associatedProducts = $groupedProduct->getAssociatedProducts();
$hasAssociatedProducts = count($associatedProducts);
	foreach ($associatedProducts as $assoc):
		$simpleProd = $assoc->getTypeId();
	endforeach;
endif;
?>
<?php if($simpleProd !='magecomp_affiliate'):?>
    <?php if ($block->getReviewsCount()): ?>
    <?php $rating = $block->getRatingSummary(); ?>
    <div class="product-reviews-summary short<?= !$rating ? ' no-rating' : '' ?>">
        <?php if ($rating):?>
        <div class="rating-summary">
            <span class="label"><span><?= $block->escapeHtml(__('Rating')) ?>:</span></span>
            <div class="rating-result" title="<?= $block->escapeHtmlAttr($rating) ?>%">
                <span style="width:<?= $block->escapeHtmlAttr($rating) ?>%"><span><?= $block->escapeHtml($rating) ?>%</span></span>
            </div>
        </div>
        <?php endif;?>
        <div class="reviews-actions">
            <a class="action view" href="<?= $block->escapeUrl($url) ?>"><?= $block->escapeHtml($block->getReviewsCount()) ?>&nbsp;<span><?= ($block->getReviewsCount() == 1) ? $block->escapeHtml(__('Review')) : $block->escapeHtml(__('Reviews')) ?></span></a>
        </div>
    </div>
    <?php elseif ($block->getDisplayIfEmpty()): ?>
    <div class="product-reviews-summary short empty">
        <div class="reviews-actions">
            <a class="action add" href="<?= $block->escapeUrl($urlForm) ?>">
                <?= $block->escapeHtml(__('Be the first to review this product')) ?>
            </a>
        </div>
    </div>
    <?php endif; ?>
<?php endif; ?>
