<?php
// @codingStandardsIgnoreFile

/** @var $block \Magento\Catalog\Block\Product\View */
?>
<?php $_helper = $this->helper('WeltPixel\ProductPage\Helper\Data'); ?>
<?php $selectMaxValue = $_helper->getQtySelectMaxValue(); ?>
<?php $_product = $block->getProduct(); ?>
<?php $buttonTitle = __('Add to Cart'); ?>
<?php $addToCartClass = !$block->shouldRenderQuantity() ? 'full-width-btn' : ''; ?>
<?php 
$simpleProd = '';
if($_product->getTypeId() == 'grouped'):
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$groupedProduct = $objectManager->create('Magento\GroupedProduct\Block\Product\View\Type\Grouped');
$associatedProducts = $groupedProduct->getAssociatedProducts();
$hasAssociatedProducts = count($associatedProducts);
	foreach ($associatedProducts as $assoc):
		$simpleProd = $assoc->getTypeId();
	endforeach;
endif;
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$affiliateFile = $objectManager->create('Webmull\AffiliateProduct\Model\AffiliateProduct\ImageUploader\FileProcessor');
?>
<?php if ($_product->isSaleable()): ?>
    <div class="box-tocart">
        <div class="fieldset">
            <?php $affiliateUrl = $affiliateFile->getMediaUrl($_product->getAffiliateBrandImage()); ?>
            <?php if($simpleProd == '' && $_product->getTypeId() == 'magecomp_affiliate'):?>
                <?php if($_product->getLinkurl() != ''):?>
                    <?php
                        if ($_product->getLinetext() != '') {
                            $linText = $_product->getLinetext();
                        } else {
                            $linText = 'Buy Now';
                        }
                    ?>
                    <div class="affiliate-image single-affi-pro">
                        <a href="<?php echo $_product->getLinkurl();?>" target="<?php echo $_product->getOpenin();?>">
                            <button type="button" title="Add to Cart" class="action primary tocart">
                                <span class="external-link"><i class="icon-external-link"></i></span>
                                <span><?php echo $linText;?></span>
                            </button>
                        </a>
            
                    </div>
                <?php endif;?>
            <?php endif;?>
            <?php if ($block->shouldRenderQuantity() && $simpleProd !='magecomp_affiliate' && $_product->getTypeId() != 'magecomp_affiliate'): ?>
                <div class="field qty">
                    <label class="label" for="qty"><span><?php /* @escapeNotVerified */ echo __('Qty') ?></span></label>
                    <div class="control">
                        <select name="qty"
                                title="<?php /* @escapeNotVerified */ echo __('Qty') ?>"
                                id="qty"
                                class="input-text qty">
                            <?php foreach (range(1, $selectMaxValue) as $number) : ?>
                                <option value="<?php echo $number ?>"><?php echo $number ?></option>
                            <?php endforeach; ?>
                        </select>
                    </div>
                </div>
            <?php endif; ?>
            <div class="actions  <?php echo $addToCartClass; ?>">
			<?php if($simpleProd !='magecomp_affiliate' && $_product->getTypeId() != 'magecomp_affiliate'):?>
                <button type="submit"
                        title="<?php /* @escapeNotVerified */ echo $buttonTitle ?>"
                        class="action primary tocart"
                        id="product-addtocart-button">
                    <span><?php /* @escapeNotVerified */ echo $buttonTitle ?></span>
                </button>
			<?php endif;?>
                <?php echo $block->getChildHtml('', true) ?>
            </div>
        </div>
    </div>
<?php endif; ?>
<?php if ($block->isRedirectToCartEnabled()) : ?>
    <script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "Magento_Catalog/product/view/validation": {
                "radioCheckboxClosest": ".nested"
            }
        }
    }
</script>
<?php else : ?>
    <script>
        require([
            'jquery',
            'mage/mage',
            'Magento_Catalog/product/view/validation',
            'Magento_Catalog/js/catalog-add-to-cart'
        ], function ($) {
            'use strict';

            $('#product_addtocart_form').mage('validation', {
                radioCheckboxClosest: '.nested',
                submitHandler: function (form) {
                    var widget = $(form).catalogAddToCart({
                        bindSubmit: false
                    });

                    widget.catalogAddToCart('submitForm', $(form));

                    return false;
                }
            });
        });
    </script>
<?php endif; ?>