<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php /* @var $block \Magento\Catalog\Block\Product\View\AbstractView */?>
<?php $_product = $block->getProduct() ?>
<?php 
$simpleProd = '';
if($_product->getTypeId() == 'grouped'):
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$groupedProduct = $objectManager->create('Magento\GroupedProduct\Block\Product\View\Type\Grouped');
$associatedProducts = $groupedProduct->getAssociatedProducts();
$hasAssociatedProducts = count($associatedProducts);
	foreach ($associatedProducts as $assoc):
		$simpleProd = $assoc->getTypeId();
	endforeach;
endif;?>

<?php if ($block->displayProductStockStatus() && $simpleProd !='magecomp_affiliate') :?>
    <?php if ($_product->isAvailable()) :?>
        <div class="stock available" title="<?= $block->escapeHtmlAttr(__('Availability')) ?>">
            <span><?= $block->escapeHtml(__('In stock')) ?></span>
        </div>
    <?php else :?>
        <div class="stock unavailable" title="<?= $block->escapeHtmlAttr(__('Availability')) ?>">
            <span><?= $block->escapeHtml(__('Out of stock')) ?></span>
        </div>
    <?php endif; ?>
<?php endif; ?>
