<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// phpcs:disable Magento2.Templates.ThisInTemplate.FoundThis

/**
 * Product view template
 *
 * @var $block \Magento\Catalog\Block\Product\View\Description
 */
?>
<?php
$_helper = $this->helper(Magento\Catalog\Helper\Output::class);
$_product = $block->getProduct();

if (!$_product instanceof \Magento\Catalog\Model\Product) {
    return;
}

$_call = $block->getAtCall();
$_code = $block->getAtCode();
$_className = $block->getCssClass();
$_attributeLabel = $block->getAtLabel();
$_attributeType = $block->getAtType();
$_attributeAddAttribute = $block->getAddAttribute();

$renderLabel = true;
// if defined as 'none' in layout, do not render
if ($_attributeLabel == 'none') {
    $renderLabel = false;
}

if ($_attributeLabel && $_attributeLabel == 'default') {
    $_attributeLabel = $_product->getResource()->getAttribute($_code)->getStoreLabel();
}
if ($_attributeType && $_attributeType == 'text') {
    $_attributeValue = ($_helper->productAttribute($_product, $_product->$_call(), $_code))
        ? $_product->getAttributeText($_code)
        : '';
} else {
    $_attributeValue = $_helper->productAttribute($_product, $_product->$_call(), $_code);
}
?>
<?php 
$simpleProd = '';
if($_product->getTypeId() == 'grouped'):
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$groupedProduct = $objectManager->create('Magento\GroupedProduct\Block\Product\View\Type\Grouped');
$associatedProducts = $groupedProduct->getAssociatedProducts();
$hasAssociatedProducts = count($associatedProducts);
	foreach ($associatedProducts as $assoc):
		$simpleProd = $assoc->getTypeId();
	endforeach;
endif;
$affiliateAttr = ['outfit_by', 'our_brand'];
?>
<?php if($simpleProd !='magecomp_affiliate' && $_product->getTypeId() != 'magecomp_affiliate'): ?>
	<?php if ($_attributeValue) :?>
	<div class="product attribute <?= $block->escapeHtmlAttr($_className) ?>">
		<?php if ($renderLabel) :?>
			<strong class="type"><?= $block->escapeHtml($_attributeLabel) ?></strong>
		<?php endif; ?>
		<div class="value" <?= /* @noEscape */ $_attributeAddAttribute ?>><?= /* @noEscape */ $_attributeValue ?></div>
	</div>
	<?php endif; ?>
<?php endif; ?>

<?php if($simpleProd =='magecomp_affiliate' || $_product->getTypeId() == 'magecomp_affiliate'): ?>
	<?php if(in_array($_code , $affiliateAttr)):?>
		<?php if ($_attributeValue) :?>
		<div class="product attribute <?= $block->escapeHtmlAttr($_className) ?>">
			<?php if ($renderLabel) :?>
				<strong class="type"><?= $block->escapeHtml($_attributeLabel) ?></strong>
			<?php endif; ?>
			<div class="value" <?= /* @noEscape */ $_attributeAddAttribute ?>><?= /* @noEscape */ $_attributeValue ?></div>
		</div>
		<?php endif; ?>
	<?php endif; ?>
<?php endif; ?>