<!-- 
/**
 * Webkul Software
 *
 * @category    Webkul
 * @package     Webkul_Blog
 * @author      Webkul
 * @copyright   Copyright (c) Webkul Software Private Limited (https://webkul.com)
 * @license     https://store.webkul.com/license.html
 */ -->
<?php
$categories = $block->getCategories();
$blogDetails = $block->getEditPostData();
$blogHelper = $this->helper('Webkul\Blog\Helper\Data');
$isLoggedIn = $blogHelper->getCustomerLoginInfo();
$isBlogger = $blogHelper->isCustomerBlogger();
if ($isLoggedIn) :
?>
    <?php if ($isBlogger) : ?>
        <form class="addPostForm"  data-mage-init='{"validation":{}}' action="<?php echo $block->escapeHtml($block->getUrl('wkblog/blog/save'))?>" method="POST" id="custom-form" data-hasrequired="<?php echo $block->escapeHtml(__('* Required Fields')) ?>">
            <div class='wk-blog-manager' id = 'wk-blog-manager'>
                
                <fieldset class="fieldset info wk-blog-fieldset">
                    <input type="hidden" id='blogid' name='blogid' value='<?php  echo $block->escapeHtml($blogDetails['id']); ?>'>
                    <div class="field required">
                        <label class="label"><?php echo $block->escapeHtml(__('Category')) ?>:</label>
                        <div class="control">
                            <select class="required-entry" name="category_id" form="custom-form" id='wk-select'>
                                <?php
                                foreach ($categories as $category) {
                                    if ($category->getId() == $blogDetails['category_id']) {?>
                                        <option value='<?php echo $block->escapeHtml($category->getId()); ?>' selected><?php  echo $block->escapeHtml($category->getCategory()); ?></option>
                                <?php
                                    } else {?>
                                        <option value='<?php echo $block->escapeHtml($category->getId()); ?>'><?php echo $block->escapeHtml($category->getCategory()); ?></option>
                                <?php
                                    }
                                }

                            ?>
                            </select>
                        </div>
                    </div>
                    <div class="field required">
                        <label class="label"><?php echo $block->escapeHtml(__('Title')) ?>:</label>
                            <div class="control">
                                <input type="text" class=' required-entry input-text'  name="subject" id="subject"  value="<?php  echo $block->escapeHtml($blogDetails['subject']); ?>">
                            </div>
                    </div>
                    <div class="field required">
                        <label class="label"><?php echo $block->escapeHtml(__('Meta Keywords')) ?>:</label>
                            <div class="control">
                                <textarea class='required-entry input-text' name='metakeywords'  value="<?php echo $block->escapeHtml($blogDetails['metakeywords']); ?>" id='metakeywords'><?php  echo $block->escapeHtml($blogDetails['metakeywords']); ?></textarea>
                            </div>
                    </div>
                    <div class="field required">
                        <label class="label"><?php echo $block->escapeHtml(__('Meta Description')) ?>:</label>
                            <div class="control">
                                <textarea class='required-entry input-text' name='metadescription' id='metadescription'><?php echo $block->escapeHtml($blogDetails['metadescription']); ?></textarea>
                            </div>
                    </div>
                    <div class="field required">
                        <label class="label">
                            <?= /* @noEscape */  $block->escapeHtml(__('Preview Description')) ?>:
                        </label>
                        <div class="control">
                        <textarea class='required-entry input-text validate-no-html-tags' name='preview'
                        value="<?= /* @noEscape */ $blogDetails['preview'] ??  "" ?>"
                        id='preview'><?= /* @noEscape */$blogDetails['preview'] ??  "" ?></textarea>
                        </div>
                    </div>

                    <div class="field required">
                        <label class="label"><?php echo $block->escapeHtml(__('Content')) ?>:</label>
                            <div class="control">
                                <textarea name="content" class="required-entry input-text" id="description"> <?php echo $blogDetails['content']; ?></textarea>       
                                 <script>
                                require([
                                    'jquery',
                                    'mage/adminhtml/wysiwyg/tiny_mce/setup'
                                ], function(jQuery){

                                    var config = '<?php echo $block->escapeHtml($block->getWysiwygConfig()) ?>',
                                        editor;

                                    jQuery.extend(config, {
                                        settings: {
                                            theme_advanced_buttons1 : 'bold,italic,|,justifyleft,justifycenter,justifyright,|,' +
                                                'fontselect,fontsizeselect,|,forecolor,backcolor,|,link,unlink,image,|,bullist,numlist,|,code',
                                            theme_advanced_buttons2: null,
                                            theme_advanced_buttons3: null,
                                            theme_advanced_buttons4: null,
                                            theme_advanced_statusbar_location: null
                                        },
                                        files_browser_window_url: false
                                    });

                                    editor = new tinyMceWysiwygSetup(
                                        'description',
                                        config
                                    );

                                    editor.turnOn();

                                    jQuery('#description')
                                    .addClass('wysiwyg-editor')
                                    .data(
                                        'wysiwygEditor',
                                        editor
                                    );
                                });
                                </script>

                            </div>
                    </div>
                    <div class="field required">
                        <label class="label"><?php echo $block->escapeHtml(__('Tag')) ?>:</label>
                            <div class="control">
                                <input type="text" class="required-entry input-text" name='tag' id='tag' value="<?php  echo $block->escapeHtml($blogDetails['tag']); ?>" >
                            </div>
                    </div>
                    <div class='wk-save-button'>
                        <button class="button" ><?php echo $block->escapeHtml(__("SAVE"));?></button>
                    </div>
                </fieldset>
            </div>   
            <div class="buttons-set">
                <p class="back-link">
                    <a class="left" onclick="javascript: window.history.back();" href="javascript:;">« Back</a>
                </p>
            </div>        
        </form>
    <?php else :?>
    <div class='WK_textcolor'> <?php echo $block->escapeHtml(__('YOU ARE NOT SUBSCRIBED TO BLOGS')); ?></div>
    <?php endif; ?>

<?php endif;

$optionElements = [
    'descriptionId' => '#description',
    'saveutton' => '.wk-save-button'
];
$serializedData = $this->helper('Magento\Framework\Json\Helper\Data')->jsonEncode($optionElements);
?>
<script type="text/x-magento-init">
{
"*":{
        "contentValidate":<?php /* @noEscape */ echo $serializedData; ?>
    }
}
</script>



