<!-- 
/**
 * Webkul Software
 *
 * @category    Webkul
 * @package     Webkul_Blog
 * @author      Webkul
 * @copyright   Copyright (c) Webkul Software Private Limited (https://webkul.com)
 * @license     https://store.webkul.com/license.html
 */ -->
<?php
$isLoggedIn = $this->helper('Webkul\Blog\Helper\Data')->isCustomerBlogger();
$customerData = $this->helper('Webkul\Blog\Helper\Data')->getLoggedInCustomerData();
$name = $customerData->getFirstname();
$email = $customerData->getEmail();
$customerId = $customerData->getId();
if (!($isLoggedIn)) {?>
    <li class='nav item'>   
        <a href='<?php  echo $block->escapeHtml($this->getUrl()); ?>wkblog/customer/addblogger/userid/<?php echo $block->escapeHtml($customerId);?>/name/<?php echo $block->escapeHtml($name);?>/email/<?php echo $block->escapeHtml($email);?>' role='button' class='btn' > <?php echo __('Subscribe For Blogs');?> </a>
    </li> 
<?php
}
?>