<!-- 
/**
 * Webkul Software
 *
 * @category    Webkul
 * @package     Webkul_Blog
 * @author      Webkul
 * @copyright   Copyright (c) Webkul Software Private Limited (https://webkul.com)
 * @license     https://store.webkul.com/license.html
 */ -->
<?php
$customerId =$block-> getcustomerId();
$collection = $block->getBlogByTag();
$limit = $this->helper('Webkul\Blog\Helper\Data')->getCharacterLimit();
$tagName = $block ->getTagName();
$collectionSize = $collection->getSize();
?>
<?php if ($collectionSize) : ?>
    <?php foreach ($collection as $blog) : ?>
        <?php $name=$blog->getCustomerName(); ?>
    <?php endforeach; ?>
    <div class = 'container'>
    <h4 class='WK_textcolor wk-heading'><?php /* @noEscape */ echo $tagName; ?></h4>
        <?php foreach ($collection as $blog) : ?>
            <div class='wk-blog-block'>
                <h2 class='WK_textcolor'> 
                <?php
                    $blogUrl = $this->getUrl().'wkblog/blog/title/blogid/'.$blog->getId();
                ?>
                <a href='<?php  echo $block->escapeUrl($blogUrl);?>'
                 role='button' class='btn'>
                 <div class='title'><?php echo $block->escapeHtml($blog->getSubject());?></div>
                 </a></h2>
                <p class ='post-meta tags' style='margin-top:20px;'>
                    <span class='date'><?php  echo $block->escapeHtml($blog->getCreatedAt());  ?> 
                    </span>
                    <?php $blogUrl = $this->getUrl().'wkblog/blog/user/userid/'.$blog->getUserId();?>
                    <a href='<?php echo $block->escapeUrl($blogUrl);?>' role='button' class='btn'>
                    <span class='author'><?php  echo $block->escapeHtml($blog->getCustomerName()); ?></span></a>
                    <?php if ($blog->getCategory() != "") : ?>
                        <?php if ($blog->getStatus() != 0) : ?>
                        <?php
                          $catUrl = $this->getUrl().'wkblog/category/category/categoryid/'.$blog->getCategoryId();
                            ?>
                            <a href='<?php echo $block->escapeUrl($catUrl);?>' 
                            role='button' class='btn'>
                            <span class='cats'><?php  echo $block->escapeHtml($blog->getCategory())?></span></a>
                        <?php endif; ?>
                    <?php endif; ?>
                </p>                
                <?php if (strlen($blog->getContent()) > $limit) : ?>
                    <?php $content = substr($blog->getContent(), 0, $limit)."..."; ?>
                <?php else : ?>
                    <?php $content = $blog->getContent(); ?>
                <?php endif; ?>
                <?php echo "<div class='WK_tbodyingedit_content'>".$content."</div>"; ?>
                <p class='tags'>
                    <span class='tag'>
                        <?php $tags = $blog->getTag();
                        $tagsArray = explode(',', $tags);
                        foreach ($tagsArray as $tag) : ?>
                            <?php if ($tag != "") :
                                $tagUrl = $this->getUrl().'wkblog/blog/tag/tag/'.$tag;?>
                                <a 
                                href='<?php echo $block->escapeHtml($tagUrl);?>' 
                                role='button' class='btn'>
                                <span class='tag'><?php echo $block->escapeHtml($tag);?> ,</span></a>
                            <?php endif; ?>
                        <?php endforeach; ?>
                    </span>
                </p>
                <hr>
            </div>  
        <?php endforeach; ?>
        <?php if ($block->getPagerHtml()) : ?>
            <div class="order-products-toolbar toolbar bottom"><?php echo $block->getPagerHtml(); ?></div>
        <?php endif; ?>
        <div class='wk-footer'>
            <div class="buttons-set">
                <p class="back-link">
                    <a class="left" onclick="javascript: window.history.back();" href="javascript:;">« Back</a>
                </p>
            </div>
        </div>
    </div>
<?php else : ?>
    <?php echo "<div class='WK_textcolor'> No Post Exist! </div>"; ?>
<?php endif; ?>     
