<?php
$customer = $this->getCustomer();

if($customer->isLoggedIn()){
	$name = $customer->getCustomer()->getName();
	$email = $customer->getCustomer()->getEmail();
} else {
	$name = '';
	$email = '';
}
?>

<div id="backgroundpopup" class="background-opacity" style="display: none; background: none; background: none repeat scroll 0% 0% rgb(0,0,0);"></div>
<div id="notify_information" class="notification-container">
	<?php
	$title = $block->getConfigValue('easymaintenance/notify/title');
	$message = $block->getConfigValue('easymaintenance/notify/message');
	$title = isset($title) ? $title : __('Notify Me!');
	?>
	<div class="notification-title">
		<?php echo $title ?>
		<div class="notification-message">
			<?php if( isset($message) && $message != null) : ?>
				<span class="notification-message"> <?php echo __($message) ?> </span>
			<?php endif; ?>
		</div>
	</div>

	<div class="notification-content">
		<form class="form" action="<?php echo $this->getControllerUrl('easymaintenance/indexcontroller/postnotify')?>" method="post" id="frm_notify" data-hasrequired="<?php /* @escapeNotVerified */ echo __('* Required Fields') ?>" data-mage-init='{"validation":{}}' onsubmit="easysiteNotify('<?php echo $this->getControllerUrl('easymaintenance/indexcontroller/postnotify')?>')">
			<div id="success_message_notify" style="display:none" class="message success-msg"></div>
			<div class="succ_button" style="text-align:center;display:none;"><button name="notifybtnsubmit" type="button" class="button-feedback" style="padding: 20px 80px 20px 80px; font-size: 30px; background: blue;">OK</button>
			<p style="height:30px;">&nbsp;</p>
			</div>
			<ul class="notify_body">
				<li>
					<label for="fname" data-bind="i18n: 'Your Full Name'"><?php echo __('Your Full Name').":" ?> <span class="required">*</span></label>
					<input name="notifyuname" value="<?php echo htmlspecialchars($name) ?>" title="<?php echo ('Name') ?>" id="notifyuname" type="text" data-validate="{required:true}" class="input-text required-entry" required />
				</li>
				<li>
					<label for="email"><?php echo __('Your E-mail').":" ?> <span class="required">*</span></label>
					<input name="notifymail" value="<?php echo htmlspecialchars($email) ?>" title="<?php echo __('Email Address') ?>" id="notifymail" type="email" data-validate="{required:true, 'validate-email':true}" class="input-text required-entry validate-email" required/>
				</li>
				<li>
					<button id="notifybtnsubmit" name="notifybtnsubmit"  type="submit" class="button-feedback">
						<span><span><?php echo __('Submit') ?></span></span>
					</button>
					<span id="loader_notify" class="loader-feedback" style="display: none; ">
						<img src="<?php echo $this->getViewFileUrl('Biztech_Easymaintenance/images/loader.gif') ?>" alt='' title=''/>
					</span>
				</li>
			</ul>
		</form>
	</div>
    
</div>
<div class="error"><span></span>
<P style="height:100px;">&nbsp;</p>

</div>