<?php
/**
 * Webkul Software.
 *
 * @category  Webkul
 * @package   Webkul_ChatGPT
 * @author    Webkul Software Private Limited
 * @copyright Webkul Software Private Limited (https://webkul.com)
 * @license   https://store.webkul.com/license.html
 */
?>
<div class="wk-chatgpt-info">
    <div>
        <p><?= /* @noEscape */__('Author') ?>:
            <a target="_blank" title="Webkul Software Private Limited"
                href="https://webkul.com/"><?= /* @noEscape */__('Webkul') ?>
            </a>
        </p>
        <p><?= /* @noEscape */ __('Version') ?>:
            <?= /* @noEscape */ $block->getModuleVersion('Webkul_ChatGPT') ?>
        </p>
        <p><?= /* @noEscape */ __('User Guide') ?>:
            <a target="_blank" href="https://webkul.com/blog/magento-2-chatgpt-ai-extension-documentation/">
                <?= /* @noEscape */ __('Click Here') ?>
            </a>
        </p>
        <p><?= /* @noEscape */ __('Store Extension') ?>:
            <a target="_blank" href="https://store.webkul.com/magento2-chatgpt-ai-extension.html">
                <?= /* @noEscape */ __('Click Here') ?>
            </a>
        </p>
        <p><?= /* @noEscape */ __('Ticket/Customisations') ?>:
            <a target="_blank" href="https://webkul.uvdesk.com/en/customer/create-ticket/">
                <?= /* @noEscape */ __('Click Here') ?>
            </a>
        </p>
        <p><?= /* @noEscape */ __('Services') ?>:
            <a target="_blank" href="https://webkul.com/magento-development/">
                <?= /* @noEscape */ __('Click Here') ?>
            </a>
        </p>
    </div>
</div>
